version: "3"

services:
  app:
    hostname: app
    image: "nikolaik/python-nodejs:python3.12-nodejs22-bullseye"
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: pn
    volumes:
      - ..:/workspace
    ports:
      - "3000:3000"  # Next.js
      - "8000:8000"  # FastAPI
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/postgres
    # command: sh -c "cd /workspace/backend && uvicorn main:app --host 0.0.0.0 --reload & cd /workspace/frontend && npm run dev"
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: