version: "3"

services:
  app:
    hostname: app
    image: "mcr.microsoft.com/devcontainers/python:3.12-bullseye"
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    volumes:
      - ..:/workspace:cached
  db:
    hostname: db
    image: "postgres:14"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: